### ISSUE TITLE
support for exlude_globs/include_globs?

### ISSUE THREAD

**Issue by henrik9999** [fregante/webext-patterns#6]
lets say i have this manifest for example
```json
{
  "name": "My extension",
  ...
  "content_scripts": [
    {
      "matches": ["https://*.nytimes.com/*"],
      "exclude_globs": ["*science*"],
      "js": ["contentScript.js"]
    }
  ],
  ...
}
```

now i would try to do something like
```js
import {patternToRegex} from 'webext-patterns';

if(patternToRegex('https://*.nytimes.com/*').test("https://www.nytimes.com/section/science") && !patternToRegex('*science*').test("https://www.nytimes.com/section/science")) {
    console.log(true)
}
```
but i get 
![image](https://user-images.githubusercontent.com/22085664/135761241-4f5c2a1c-5f6e-4d2d-adbf-83d138c53df0.png)

could support for these globs be added?

**Comment by fregante** [comment]
Patterns have different behaviors from generic globs, so if implemented it would be its own export/function. I don't have time to research and implement this now, but I'd accept a PR
